namespace Stratezone.Simulation.Content;

public sealed record BuildingDefinition(
    string Id,
    string DisplayName,
    string Role,
    int Cost,
    int Health,
    IReadOnlyDictionary<string, float> DamageResistances,
    float FootprintRadius,
    float PlacementBuffer,
    bool RequiresPower,
    bool ProvidesPower,
    float PowerRadius,
    float PylonLinkRange,
    bool ProvidesResourceExtraction,
    string? ExtractorResourceId,
    string? RequiresAdjacentBuildingId,
    IReadOnlyList<string> TrainingUnlockUnitIds,
    bool WallAnchor,
    float WallLinkRange,
    float AttackDamage,
    float AttackRange,
    float AttackCooldown,
    string DamageType,
    float AreaRadius,
    bool FriendlyFire,
    IReadOnlyList<string> TargetFilters,
    string? UpgradeFromBuildingId,
    bool UpgradePreservesWallAnchor,
    float SightRange,
    IReadOnlyList<string> Tags
);
